require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

RSpec/FilePath:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
