require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
