services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/postgres
      JWT_SECRET: JWT_SECRET
    depends_on:
      - db
    ports:
      - "3600:3000"   
    command: bash -c "bundle exec rails db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata2:
