services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "3600:3000"
    command: rails s -p 3000 -b '0.0.0.0'
    # command: rails db:setup
    tty: true
    stdin_open: true # for debugging: "docker compose up -d && docker compose attach app"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
