default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_DEVELOPMENT_NAME', "todo-graphql_development") %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_TEST_NAME', "todo-graphql_test") %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_PRODUCTION_NAME', "todo-graphql_production") %>
