default: &default
  adapter: postgresql
  timeout: 10000
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  encoding: utf8

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') %>
